dc-all-minilm-l6-v2:
  index: "dc-all-minilm-l6-v2-index"
  model: "dc-all-minilm-l6-v2-model"

uae-large-v1:
  index: "uae-large-v1-index"
  model: "uae-large-v1-model"

sfr-embedding-mistral:
  index: "sfr-embedding-mistral-index"
  model: "sfr-embedding-mistral-model"

cross-encoder-ms-marco-miniilm-l6-v2:
  model: "cross-encoder-ms-marco-miniilm-l6-v2"

cross-encoder-mxbai-rerank-base-v1:
  model: "cross-encoder-mxbai-rerank-base-v1"